# ----------------------------
# Program Options
# ----------------------------

NAME         ?= FLIPFROG
ICON         ?= icon.png
DESCRIPTION  ?= "FLIPFROG v1.0"
COMPRESSED   ?= YES
ARCHIVED     ?= NO
# ----------------------------
# Compile Options
# ----------------------------


CFLAGS ?= -Wall -Wextra -Oz
CXXFLAGS ?= -Wall -Wextra -Oz

# ----------------------------
# Debug Options
# ----------------------------

OUTPUT_MAP   ?= NO

include $(CEDEV)/meta/makefile.mk
